services:

  mysql:
    image: mysql:8.0
    container_name: tienda_pepe_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tienda_pepe
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: tienda_pepe_backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: tienda_pepe
      DB_PORT: 3306
      PORT: 3001
    depends_on:
      - mysql

volumes:
  mysql_data: